# -*- coding: utf-8 -*-
"""ques11a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#11. Modules cal1.py and m5.py

#cal1.py

def add1(x, y):
  return x + y

def sub1(x, y):
  return x - y

def mul1(x, y):
  return x * y

def div1(x, y):
  if y == 0:
    raise ZeroDivisionError("Division by zero")
  return x / y

def mod1(x, y):
  return x % y

def pow1(x, y):
  return x ** y