# -*- coding: utf-8 -*-
"""ques12b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#12. Package with list1.py, set2.py, dict3.py, m5.py, and m6.py

#set2.py:

def slen2(s):
    return len(s)

def adds2(x, s):
    s.add(x)
    return s

def remove2(x, s):
    s.remove(x)
    return s