# -*- coding: utf-8 -*-
"""ques9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#9. Multiple Except Blocks

try:
    # Some code that may raise exceptions
    result = 10 / 0
    print(undefined_variable)
except (ZeroDivisionError, NameError, TypeError) as e:
    print(f"An error occurred: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")