# -*- coding: utf-8 -*-
"""ques12c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#12. Package with list1.py, set2.py, dict3.py, m5.py, and m6.py

#dict3.py:

def len3(d):
    return len(d)

def add3(k, v, d):
    d[k] = v
    return d

def keys3(d):
    return d.keys()

def values3(d):
    return d.values()