# -*- coding: utf-8 -*-
"""ques12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#12. Package with list1.py, set2.py, dict3.py, m5.py, and m6.py

#Package Structure:

my_package/
  __init__.py
  list1.py
  set2.py
  dict3.py
  m5.py
m6.py