# -*- coding: utf-8 -*-
"""ques7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#7. FileNotFoundError Handler

try:
  with open("nonexistent_file.txt", "r") as file:
    content = file.read()
except FileNotFoundError:
  print("Error: File not found")