# -*- coding: utf-8 -*-
"""ques8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#8. ModuleNotFoundError Handler

try:
  import non_existent_module
except ModuleNotFoundError:
  print("Error: Module not found")