# -*- coding: utf-8 -*-
"""ques6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#6. AttributeError Handler

try:
    x = 10
    x.append(5)
except AttributeError:
    print("Error: Attribute does not exist")