# -*- coding: utf-8 -*-
"""ques5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#5. ValueError Handler

try:
  int("abc")
except ValueError:
  print("Error: Invalid value for data type conversion")