# -*- coding: utf-8 -*-
"""ques11b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#11. Modules cal1.py and m5.py

#m5.py

import cal1

result_add = cal1.add1(5, 3)
result_sub = cal1.sub1(10, 4)
result_mul = cal1.mul1(2, 6)
result_div = cal1.div1(12, 3)
result_mod = cal1.mod1(10, 3)
result_pow = cal1.pow1(2, 5)