# -*- coding: utf-8 -*-
"""ques2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#2 NameError Handler

try:
  print(undefined_variable)
except NameError:
  print("Error: Variable not defined")