# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5rRQX7Cq8GZtY5mfN4OsjBAbV3DzwYk

1. ZeroDivisionError Handler
"""

try:
  result = 10 / 0
except ZeroDivisionError:
  print("Error: Division by zero")